### ISSUE TITLE
Thankyou

### ISSUE THREAD

**Issue by stuaxo** [smspillaz/libanimation#14]
Thanks for wobbly windows, and related animations!

I've been missing these since moving to gnome-shell, look forward to libanimation maturing, and being able to use a gnome-shell build with windows that can wobble once more.

**Comment by smspillaz** [comment]
Hey, thanks for the comment @stuaxo 

I want to clarify that libanimation is merely a math library and while I've prototyped integrating it with GNOME-Shell, I (nor Endless) are by no means *bringing it* to GNOME-Shell upstream: eg, you should not expect this in an upcoming release.

Of course, if the GNOME Shell maintainers would like to use it or integrate with it somehow, that's up to them.

**Comment by stuaxo** [comment]
Yup, this is all true.

Optional features like wobbly windows bring happiness to the user, but it seems like there is less room for this in gnome proper, it seems to get sacrificed to productivity and use cases.

**Comment by nightsky30** [comment]
Yes, thank you for your contributions.  I wish more desktop environments included options like those compiz allowed.  I hope your library gets much use in the future :)

> Optional features like wobbly windows bring happiness to the user, but it seems like there is less room for this in gnome proper, it seems to get sacrificed to productivity and use cases.

And yet they force us to use an annoying hot corner activity switcher which we hit inadvertently with our mice all the time.  And the stupid thing can't be disabled unless we download a third party gnome extension.  Where is the productivity in that.  The user should at least have the option.
